CC = cc
CFLAGS = -Wall -g -Icore
CFLAGS += $(shell pkg-config --cflags gtk+-3.0 gmodule-2.0)
LIBS = $(shell pkg-config --libs gtk+-3.0 gmodule-2.0)

OBJS = core/hash.o
OBJS += core/header.o
OBJS += core/ips.o
OBJS += core/rom.o

OBJS += gtk/cirugia.o

all: cirugia

cirugia: $(OBJS)
	$(CC) -o cirugia $(OBJS) $(LIBS)

clean:
	rm -f $(OBJS) cirugia
